package com.oasis.designsystem.icon

import androidx.annotation.DrawableRes
import com.oasis.designsystem.R

enum class OasisIconVariant(@DrawableRes val resId: Int) {
    ARROW_DOWN(R.drawable.oasis_ic_arrow_down),
    ARROW_LEFT(R.drawable.oasis_ic_arrow_left),
    ARROW_O_DOWN(R.drawable.oasis_ic_arrow_o_down),
    ARROW_O_TOP(R.drawable.oasis_ic_arrow_o_top),
    ARROW_RIGHT(R.drawable.oasis_ic_arrow_right),
    ARROW_UP(R.drawable.oasis_ic_arrow_up),
    AVATAR_USER_ICON(R.drawable.oasis_ic_avatar_user_icon),
    AVATAR_USER_INITIAL(R.drawable.oasis_ic_avatar_user_initial),
    AVATAR_USER_PICTURE(R.drawable.oasis_ic_avatar_user_picture),
    BELL(R.drawable.oasis_ic_bell),
    BPJS_STATE(R.drawable.oasis_ic_bpjs_state),
    BURGER_MENU_1(R.drawable.oasis_ic_burger_menu_1),
    BURGER_MENU_2(R.drawable.oasis_ic_burger_menu_2),
    CALCULATOR(R.drawable.oasis_ic_calculator),
    CALCULATOR_ALT2(R.drawable.oasis_ic_calculator_alt2),
    CALENDAR(R.drawable.oasis_ic_calendar),
    CALL(R.drawable.oasis_ic_call),
    CAMERA(R.drawable.oasis_ic_camera),
    CART(R.drawable.oasis_ic_cart),
    CHAT(R.drawable.oasis_ic_chat),
    CHECK(R.drawable.oasis_ic_check),
    CHECK_O(R.drawable.oasis_ic_check_o),
    CHEVRON_DOWN(R.drawable.oasis_ic_chevron_down),
    CHEVRON_LEFT(R.drawable.oasis_ic_chevron_left),
    CHEVRON_RIGHT(R.drawable.oasis_ic_chevron_right),
    CHEVRON_UP(R.drawable.oasis_ic_chevron_up),
    CLOCK(R.drawable.oasis_ic_clock),
    CLOSE(R.drawable.oasis_ic_close),
    COPY(R.drawable.oasis_ic_copy),
    COPY_2(R.drawable.oasis_ic_copy_2),
    DANGER_STATE(R.drawable.oasis_ic_danger_state),
    EDIT(R.drawable.oasis_ic_edit),
    EXCLAMATION_O(R.drawable.oasis_ic_exclamation_o),
    EYE_VIEW_OFF(R.drawable.oasis_ic_eye_view_off),
    EYE_VIEW_ON(R.drawable.oasis_ic_eye_view_on),
    FAQ(R.drawable.oasis_ic_faq),
    FAVORITE(R.drawable.oasis_ic_favorite),
    FILE(R.drawable.oasis_ic_file),
    FINGERPRINT(R.drawable.oasis_ic_fingerprint),
    FORBIDEN(R.drawable.oasis_ic_forbiden),
    GIFT(R.drawable.oasis_ic_gift),
    HELP_CENTER(R.drawable.oasis_ic_help_center),
    HISTORY(R.drawable.oasis_ic_history),
    HOME(R.drawable.oasis_ic_home),
    INFO_STATE(R.drawable.oasis_ic_info_state),
    INFORMATION_O(R.drawable.oasis_ic_information_o),
    KEBAB(R.drawable.oasis_ic_kebab),
    LIGHT_BULB(R.drawable.oasis_ic_light_bulb),
    LINK(R.drawable.oasis_ic_link),
    LISTRIK_PLN_STATE(R.drawable.oasis_ic_listrik_pln_state),
    LOAN_FINISHED_ALT2(R.drawable.oasis_ic_loan_finished_alt2),
    LOCK_CLOSED(R.drawable.oasis_ic_lock_closed),
    LOCK_OPEN(R.drawable.oasis_ic_lock_open),
    LOGOUT(R.drawable.oasis_ic_logout),
    MAP(R.drawable.oasis_ic_map),
    MINUS(R.drawable.oasis_ic_minus),
    MINUS_O(R.drawable.oasis_ic_minus_o),
    MOBILE_PHONE(R.drawable.oasis_ic_mobile_phone),
    MONEY(R.drawable.oasis_ic_money),
    MONEY_FAST(R.drawable.oasis_ic_money_fast),
    MONEY_IN(R.drawable.oasis_ic_money_in),
    MONEY_OUT(R.drawable.oasis_ic_money_out),
    MONEY_TOP_UP_STATE(R.drawable.oasis_ic_money_top_up_state),
    MONEY_TRANSFER_STATE(R.drawable.oasis_ic_money_transfer_state),
    MONEY_WITHDRAWAL(R.drawable.oasis_ic_money_withdrawal),
    OFFICE_BUILDING(R.drawable.oasis_ic_office_building),
    OTP_ICON(R.drawable.oasis_ic_otp_icon),
    PAKET_DATA_STATE(R.drawable.oasis_ic_paket_data_state),
    PASSWORD(R.drawable.oasis_ic_password),
    PDAM_STATE(R.drawable.oasis_ic_pdam_state),
    PIN_ICON(R.drawable.oasis_ic_pin_icon),
    PLUS(R.drawable.oasis_ic_plus),
    PLUS_O(R.drawable.oasis_ic_plus_o),
    PULSA_STATE(R.drawable.oasis_ic_pulsa_state),
    QRIS(R.drawable.oasis_ic_qris),
    RECEIPT(R.drawable.oasis_ic_receipt),
    RECEIPT_TAX(R.drawable.oasis_ic_receipt_tax),
    SEARCH(R.drawable.oasis_ic_search),
    SETTING(R.drawable.oasis_ic_setting),
    SHARE(R.drawable.oasis_ic_share),
    SUCCESS_STATE(R.drawable.oasis_ic_success_state),
    TRASH_BIN(R.drawable.oasis_ic_trash_bin),
    USER(R.drawable.oasis_ic_user),
    WARNING_STATE(R.drawable.oasis_ic_warning_state);

    companion object {
        fun from(value: Int): OasisIconVariant =
            values().getOrElse(value) { ARROW_LEFT }
    }
}